apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  annotations:
    crossplane.io/external-name: test-dynamo-dmaganto #force-naming
  name: test-dynamo-dmaganto
spec:
  forProvider:
    attributeDefinitions:
      - attributeName: attribute1
        attributeType: S
    keySchema:
      - attributeName: attribute1
        keyType: HASH
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    region: eu-west-1
  providerConfigRef:
    name: provider-config-aws