apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: test-bucket-dmaganto
  name: test-bucket-dmaganto
spec:
  forProvider:
    accelerateConfiguration:
      status: Enabled
    acl: private
    corsConfiguration:
      corsRules:
        - allowedHeaders:
            - "*"
          allowedMethods:
            - GET
          allowedOrigins:
            - "*"
          exposeHeaders:
            - x-amz-server-side-encryption
    lifecycleConfiguration:
      rules:
        - expiration:
            days: 15
          filter:
            prefix: ola/
          status: Enabled
    locationConstraint: eu-west-1
    objectLockEnabledForBucket: false
    publicAccessBlockConfiguration:
      blockPublicPolicy: true
#    replicationConfiguration:
#      roleRef:
#        name: somerole
#      rules:
#        - deleteMarkerReplication:
#            status: Disabled
#          destination:
#            bucketRef:
#              name: repl-dest
#            storageClass: STANDARD
#          filter:
#            prefix: ""
#          id: rule-1
#          priority: 0
#          status: Enabled
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    tagging:
      tagSet:
        - key: key1
          value: val1
        - key: secondKey
          value: val2
        - key: key3
          value: val3
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: provider-config-aws